name: GitHub Pages Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    - name: asciidoctor-ghpages
      env:
            SRC_FOLDER_PATH: '.'
            TARGET_BRANCH: 'gh-pages'
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        pdf_build: false
        # asciidoctor_params: --attribute=nofooter
        # adoc_file_ext: .ascii # default is .adoc
        source_dir: asciidoc/ # default is .
        # slides_build: true
        # pre_build:
        post_build: files=$(find $SRC_FOLDER_PATH -type f); git config --global user.name 'GitHub Action'; git config --global user.email 'action@github.com'; git fetch; git checkout $TARGET_BRANCH; git checkout ${GITHUB_REF##*/} -- $files; git add -A; git diff-index --quiet HEAD ||  git commit -am "deploy files"; git push origin $TARGET_BRANCH
